Fix type annotations for xml_field_validator/serializer
There are 2 issues with the annotations:

1. Function types are contravariant rather than covariant in their
   argument types. This means that `Callable[[BaseXmlModel], Any]` is a
   subtype rather than a supertype of `Callable[[MyModel], Any]` and so
   using `Callable[[BaseXmlModel], Any]` as a lower bound of TypeVars
   doesn't work. Since Python doesn't support upper bounds on TypeVars,
   the solution is to push the TypeVar inside. To see the issue run mypy
   on the example from the documentation[1]. Currently, you get these
   errors:

```
t.py:13: error: Value of type variable "ValidatorFuncT" of function cannot be "Callable[[type[Plot], XmlElementReader, str], list[float]]"  [type-var]
t.py:21: error: Value of type variable "SerializerFuncT" of function cannot be "Callable[[Plot, XmlElementWriter, list[float], str], None]"  [type-var]
```

   This PR resolves these (however, validate_space_separated_list needs
   to be decorated with @classmethod).

2. A recent commit[2] has a typo where ValidatorFuncT was bound by
   SerializerFunc instead of ValidatorFunc.

[1] https://pydantic-xml.readthedocs.io/en/latest/pages/misc.html#custom-xml-serialization
[2] https://github.com/dapper91/pydantic-xml/commit/ec4b547340b34fec395f036256eeb1e648cfee98